psql AsoiafDWH -f Tables/F_EventInChapter.sql
psql AsoiafDWH -f Tables/D_Character.sql
psql AsoiafDWH -f Tables/D_Chapter.sql
psql AsoiafDWH -f Tables/D_Book.sql
psql AsoiafDWH -f Tables/D_Gender.sql
psql AsoiafDWH -f Tables/D_Culture.sql
psql AsoiafDWH -f Tables/D_House.sql
psql AsoiafDWH -f Tables/D_Region.sql
psql AsoiafDWH -f Tables/D_Possession.sql
psql AsoiafDWH -f Tables/D_PossessionType.sql
psql AsoiafDWH -f Tables/F_PossessionOfHouse.sql
